name: t2
version: 0.1.0.0
github: "skypartan/paradigmas-t2"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2022 Author name here"

dependencies:
- base >= 4.7 && < 5
- text
- cassava
- bytestring
- vector

library:
  source-dirs: src

executables:
  t2-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - t2

tests:
  t2-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - t2
